### ISSUE TITLE
Testele pentru kafka esueaza la crearea unui consumer

### ISSUE THREAD

**Issue by rredpoppy** [gov-ithub/asistentul_cetateanului_institutii#4]
Cel mai probabil este legat de lipsa unor proprietati:

```
Tests in error: 
com.govac.institutii.KafkaTest.testMessageDelivery(com.govac.institutii.KafkaTest)
  Run 1: KafkaTest.before:60->createAndStartConsumer:96->createConsumerConfig:131 » NullPointer
  Run 2: KafkaTest.after:126 NullPointer

com.govac.institutii.KafkaTest.testSynchronousMessageDelivery(com.govac.institutii.KafkaTest)
  Run 1: KafkaTest.before:60->createAndStartConsumer:96->createConsumerConfig:131 » NullPointer
  Run 2: KafkaTest.after:126 NullPointer
```

**Comment by omulplajei** [comment]
In application.properties.dist exista cateva proprietati legate de Kafka/Zookeeper
Mai precis:
#Kafka consumer properties
zookeeper.connect=ZOOKEEPER_IP:2181
group.id=testGroupId
auto.offset.reset=smallest

Trebuie sa pui ZOOKEEPER_IP la valoarea IP-ului de zookeeper.

Nota: e confuza si pentru mine configurarea asta cu fisiere de prorietati *.dist care trebuie modificate pentru a putea rula aplicatia. O sa incerc pana una alta sa adaug in readme toate proprietatile care trebuie editate

**Comment by rredpoppy** [comment]
@omulplajei that's the thing, nu exista. ai tu pe undeva fisierul ala? noi am pus la .gitignore tot ce se termina in .properties ca sa nu scapam ceva parole pe live din neatentie

**Comment by omulplajei** [comment]
sunt aici https://github.com/gov-ithub/asistentul_cetateanului_institutii/blob/master/src/test/resources/application.properties.dist 
Trebuie sa le adaugi in versiunea ta locala de properties.
Nota: exact problema de genul asta e un indiciu ca nu e o solutie prea buna. as prefera ceva de genul director separat cu local-env, prod-env si o modalitate clara de a sti ce hostname-uri sau porturi trebuie sa editezi. o sa incerc sa adaug un exemplu.

Daca tot nu merge sa imi zici.

**Comment by rredpoppy** [comment]
Merge, thx.
